### ISSUE TITLE
Download archived threads

### ISSUE THREAD

**Issue by aqedrftgyhuj** [SuperGouge/ChanThreadWatch#41]
Would it be possible to make CTW download threads from third party archives (such as archive.moe, imcute.yt, rbt.asia, and so on), with all the files with original filenames?

**Comment by SuperGouge** [comment]
This was partially already request in #38 and basic support was added. This will be in the next release (sorry for its delay). I'll try to add as much features for Fuuka and FoolFuuka archive sites as there is for 4chan (original filenames, posters names, ...).

**Comment by aqedrftgyhuj** [comment]
Sorry, didn't dee it.
Thank you very much for the effort.
