### ISSUE TITLE
Window size bug

### ISSUE THREAD

**Issue by SatoMew** [SuperGouge/ChanThreadWatch#42]
I'm using Windows 8.1 on a screen with high PPI and the Windows GUI is DPI-scaled. Since Chan Thread Watch does not support DPI scaling, I set the flag in the executable that disables DPI virtualization. However, this is causing a very odd issue: the window resizes every time the app is run and each subsequent run makes the window bigger. Resetting the flag for DPI virtualization fixes the issue.

Even if this issue is patched, I think that [support for DPI scaling](https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266(v=vs.85).aspx) should be added in a future release.

**Comment by SuperGouge** [comment]
What happens when you don't disable DPI virtualization? CTW is supposed to support scaling.

**Comment by SatoMew** [comment]
When DPI virtualization is enabled for CTW, Windows applies it to the app as if it were not DPI-aware. In my case, the DPI is scaled by 150% but CTW instead appears blurry due to the scaled-up 100% DPI.

Here's how it looks with DPI virtualization enabled (default):

![ctw_dpiv](https://cloud.githubusercontent.com/assets/11246438/6431299/3bea56be-c023-11e4-8a42-ed34bbf3dc81.png)

And with DPI virtualization disabled:

![ctw_nodpiv](https://cloud.githubusercontent.com/assets/11246438/6431300/4877ca24-c023-11e4-81fb-2f0115f2d006.png)

The bug occurs in the latter case and only in subsequent runs of the app since it's fine on the first run (which is what the above screenshot shows).

**Comment by SuperGouge** [comment]
The bug should be fixed in the next release. I'll see about the DPI-awareness issue but my setup doesn't allow me to test this specific issue effectively for the moment.

**Comment by SatoMew** [comment]
It's fixed now, thanks :)
