### ISSUE TITLE
Option to automatically rename problematic file names

### ISSUE THREAD

**Issue by Jackomel** [SuperGouge/ChanThreadWatch#43]
When the option to save images with the original filename is activated sometimes some "problematic" files are saved.
These files usually contain long japanese text or even weird unicode strings that might even save correctly but start causing a bunch of issues when trying to move them around the file system, usually resulting in "filename too long for the file system" errors that are hard to avoid.

For example I dump threads on google drive at work so I can easily retrieve them from home but sometimes I end up with unmoveable or unsyncable files with long japanese names.

So to avoid this problem there should be a check on the name to see if it contains strings accepted by the file system and either purge the offending strings or just downloading with the filename automatically assigned by 4chan for those specific cases.

**Comment by SuperGouge** [comment]
This is already what is done. Every filename is sanitized for the file system and if it is too long the original filename will not be used.

If you frequently move around files from and to folder locations with different hierarchical depths, I suggest you don't use the original filenames. Unfortunately, there's nothing else CTW can do about it.
