### ISSUE TITLE
Add thread count to title bar

### ISSUE THREAD

**Issue by ohhdemgirls** [SuperGouge/ChanThreadWatch#50]
I have no idea how many threads I'm archiving so it would be nice to have that info in the title bar, please, thank you.

**Comment by SuperGouge** [comment]
There's already info about all the threads when right clicking the tray icon. Is that not what you want?

**Comment by ohhdemgirls** [comment]
Nope, right now my archiver [looks like this,](https://i.imgur.com/0yMGQgt.png) VM running on a 3rd monitor I glance at now and again, I don't interact with it aside from clicking 'Add From Clipboard', so adding something like **Currently Archiving ### Threads** to the title bar would be super nice and maybe even the date/time the last thread was added, often I'm archiving 100's of threads and would just like a current count.

**Comment by SuperGouge** [comment]
I'll try to add a way of customizing the title. Meanwhile, don't forget to turn on the "Minimize to tray" setting to enable the tray icon (something I might also change) and get the info.
