### ISSUE TITLE
Thread Folder Naming

### ISSUE THREAD

**Issue by 2mg** [SuperGouge/ChanThreadWatch#53]
*Informative question*

Are these features working: Description,Category,Parent Thread Description?

I'm haven't been using them, but I just spent almost an hour to give them a run, checking them out and reading the wiki, and none seem to work on 4chan tho, only Slugs/Thread IDs do.

**Comment by SuperGouge** [comment]
All those features work on any site. But changing them in the settings doesn't apply them immediately to your previously added threads being watched. You have to either wait for a ``Check``, trigger one yourself (or a restart for dead threads) or edit the thread.

**Comment by 2mg** [comment]
Of course, I tried it on a thread, each time deleting it and adding it as a new one, no change.

**Comment by SuperGouge** [comment]
Does the log file contains any error? It should be located in ``%AppData%\Chan Thread Watch``.

**Comment by 2mg** [comment]
Nope. Clean as a whistle.

Don't sweat about it, if no-one is complaining about it. I just gave it a shot and nothing happened, only bottom folder naming options worked (slug/ID).

**Comment by 2mg** [comment]
Can I go off-topic and ask, when are post reply links going to be fixed? I see only links to a post, but not from a post:

![Uploading example.gif…]()
