### ISSUE TITLE
Missing post reply links

### ISSUE THREAD

**Issue by 2mg** [SuperGouge/ChanThreadWatch#54]
When are reply links going to be added/fixed? I see reply links back to a post, but not links from that post:

(original/CTW) 
![example](https://cloud.githubusercontent.com/assets/7749968/9166061/c8988984-3f51-11e5-8ee1-4ed5e84ce8f3.JPG)

**Comment by SuperGouge** [comment]
A lot of features on imageboards are added by extensions in JavaScript and are intended to be run on the original page. Those cannot work when browsing the page locally.
