### ISSUE TITLE
Option to not download thumbnails

### ISSUE THREAD

**Issue by roukaour** [SuperGouge/ChanThreadWatch#55]
I don't always need the thumbnail images, and many small files take up surprisingly much space. I'd like an option to not download them.

**Comment by SuperGouge** [comment]
There is an [option](https://github.com/SuperGouge/ChanThreadWatch/wiki/Features#Save_Thumbnails_and_PostProcess_HTML) for that in the settings. Note that this also disables the creation of the HTML file.
