### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by zawanon** [SuperGouge/ChanThreadWatch#56]
"Already Running - Another instance of this program is running"

Can we get multiple instances again like in 4.11.2? I'm running separate CTWs from different folders for sorting and throttling purposes.

**Comment by SuperGouge** [comment]
You can run multiple instances as long as they don't use the same settings file. You can change [this setting](https://github.com/SuperGouge/ChanThreadWatch/wiki/Features#Settings_Location) so that each executable has its own settings file.

**Comment by zawanon** [comment]
Found the setting. Works fine now, thanks.
