### ISSUE TITLE
Program downloading random threads

### ISSUE THREAD

**Issue by seagull** [SuperGouge/ChanThreadWatch#57]
This seems to have something to do with tags. I set up a new tag ("tech") and watched a thread on /g/ with it. By morning, I had seventeen new threads on CTW, none of which I had added, mostly from /g/ but also from boards like /qa/ and /po/.

Sorry I can't be more substantive but there's no logfile or anything.

**Comment by SuperGouge** [comment]
Did you enable Auto-Follow for this thread? That should be why. Also there's an [option](https://github.com/SuperGouge/ChanThreadWatch/wiki/Features#Follow_Threads_Outside_of_the_Current_Board) to avoid following threads from other boards.

**Comment by seagull** [comment]
99% likely that's what it is. Thanks; I guess I didn't look through the settings clearly enough.
