### ISSUE TITLE
CTW no longer working on 4chan since 11/16/2015

### ISSUE THREAD

**Issue by Sachoriya** [SuperGouge/ChanThreadWatch#59]
not exactly sure what happened but noticed CTW isn't fetching images anymore from 4chan. was just curious if there will be a new version soon?

**Comment by SuperGouge** [comment]
It seems to be working fine with me. Does this behavior occur on a specific board?

**Comment by Sachoriya** [comment]
hmmmm......weird. and yeah, for the main board i visit /co/ it doesn't seem to grab images anymore. haven't tried any of the others. but thanks for letting me know it's not the program.

**Comment by Sachoriya** [comment]
nevermind again Supergouge. i apologize for wasting your time again, but i found out my problem which was the same before. is somehow my internet settings got changed to a proxy instead of automatic and for some reason it messes with my chanthreadwatch. still not really sure why or how it does that. but thanks again for the feedback much appreciation!

**Comment by SuperGouge** [comment]
Glad you could sort it out!
