### ISSUE TITLE
Compatibility with 8chan's new "Infinity Next" software (rolling out this month)

### ISSUE THREAD

**Issue by Elevon** [SuperGouge/ChanThreadWatch#60]
Infinity Next is currently being used under beta.8ch.net, but it is planned for the main site to be migrated over this month. Attempting to add threads from beta.8ch.net results in "Stopped: Unknown Error". Presumably when the main site starts using it CTW will cease to be compatible with 8chan.

Some threads to test with:
http://beta.8ch.net/next/
http://beta.8ch.net/v/

Next itself in case that's useful to you:
https://github.com/infinity-next/infinity-next

It's possible they could still make more UI changes that break compatibility, but it still seems good to let you know now rather than waiting for the main site to switch over.

**Comment by Sinihopea** [comment]
Thanks for the heads up.

**Comment by DerSandmann-Badcode** [comment]
Not anymore... "Infinity Next" was cancelled.
