### ISSUE TITLE
LynxChan Support

### ISSUE THREAD

**Issue by TheJellyBeanKing** [SuperGouge/ChanThreadWatch#62]
Just wanted to see if you would add support for LynxChan the biggest site that uses LynxChan at the moment is endchan.xyz.

Board to test it on:
https://endchan.xyz/v/
https://endchan.xyz/operate/

The engines source code if it helps. https://gitgud.io/LynxChan/LynxChan

**Comment by odilitime** [comment]
There's also a 4chan compat API at http://endchan.xyz:9090/ like http://endchan.xyz:9090/boards.js
