### ISSUE TITLE
Adding the Archive (archived.moe)

### ISSUE THREAD

**Issue by hardliner5000** [SuperGouge/ChanThreadWatch#67]
It might be useful  to be able to support the new archive (_**archived.moe**_). It's not compatible with the recent version. Would that be possible please? Thanks a lot for the great effort and awesome share.

**Comment by DerSandmann-Badcode** [comment]
beyond me, it's acting odd because the full images are actually hosted at archive.nyafuu.org

**Comment by SuperGouge** [comment]
Support was added for the archive. Unfortunately, the site does not use standard HTTP redirect to redirect to the full images (hosted on other archive sites). This means full images cannot be properly retrieved.

**Comment by hardliner5000** [comment]
Is there a possibility to fix the full Images issue?

**Comment by DerSandmann-Badcode** [comment]
Full images should be fixed now. I've added a SiteHelper that reads their meta redirect URLs and gets the actual resource.

**Comment by SuperGouge** [comment]
This is now fixed thanks to #78.
