### ISSUE TITLE
Images not downloading

### ISSUE THREAD

**Issue by hardliner5000** [SuperGouge/ChanThreadWatch#69]
Recently I've noticed that the totality of the jpgs are not downloading. I have to stop-start the thread to download everything.
It's always the same server/url:
https://i.4cdn.org/*/*
I thought there're more image servers but it seems to be just one.

Thanks a lot for your great effort.

**Comment by SuperGouge** [comment]
Are you using the latest version (1.15.1)?

**Comment by hardliner5000** [comment]
Yes the very last version on a brand new PC with the configuration:
-i5 6600k
-z170-A Pro
-Windows 7 x64
CTW Is freezing sometimes and crashes. 
On my old PC with the 1.14.0 version it ran very stable though. It didn't download the complete Images but it was caused by the two diffrent image server recently added.

Thanks

**Comment by SuperGouge** [comment]
I'm sorry but I can't seem to reproduce this issue on my end.

- Are you behind a VPN/proxy?
- How are you adding the thread? (from clipboard, manually, ...)
- Does it happen on every site? On every board? On every thread?
- Does it happen for every type of media? (images, webm, ...)

If you have reproducible steps please provide them.

Also, if you're having other problems with the latest version, please open a separate issue.

**Comment by hardliner5000** [comment]
Thanks for your reply, based SuperGouge.
To answer your question:
 ● No Proxy/ VPN.
 ● Adding the threads manually.
 ● It happens on one board, multiple threads.
 ● Happens with all sort of media.

**Comment by SuperGouge** [comment]
Did you try it on other boards? If it really only happens on this board can you tell me which one it is?

**Comment by hardliner5000** [comment]
Yes I did. /b/ /soc/ /hc/ /gif/ /pol/ /g/
It seems to be some sort of a troubleshoot or a bug with the application (executable) itself.
That would explain why it crashes (freeze) while downloading as well? 
I even deactivated my AV. And set an exception for the *.exe file.

**Comment by SuperGouge** [comment]
So the bug happens on all these boards?
How long is the path to the download folder?

Can you also post your "log.txt" file located at "%AppData%\Chan Thread Watch" please?

**Comment by hardliner5000** [comment]
Default download folder. I'll post the log file as soon as possible.
BTW I had a sudden blank thread.txt 2 days ago.

**Comment by githubisforcingmetodothis** [comment]
Not sure if the procedure is to make a new issue or what, but I think I have found the pattern for the error:

For whatever reason, any address http://is.4chan.org will not be saved by the program, regardless of what board it is, or if it's archived or not.

For example, this thread:
http://boards.4chan.org/co/thread/88252374

Will not save any pictures despite it having one. Even more odd, if you were to grab that picture link you can't save:
http://is.4chan.org/co/1481164089838.gif

And turn it into a link like the other pictures like before:

http://i.4cdn.org/co/1481164089838.gif

The picture will actually work, and thus most likely be saved.

Just thought to mention it so maybe a fix or a workaround can be done.

**Comment by hardliner5000** [comment]
Thanks @githubisforcingmetodothis 
I'm glad to see its not only me with this troubleshoot.
Anyone else getting constantly a blank thread.txt?

**Comment by SuperGouge** [comment]
The thread you linked works just fine for me on version 1.15.1. In latest versions, the program does not care what is the URL of the media, it parses what to download based on HTML structure solely.

Maybe your computer has problems downloading from this particular subdomain. Does the thread stops from an error? Can you share your log file?

**Comment by jwshields** [comment]
RE: blank threads.txt
Do you have autobackup enabled? It's a lifesaver if that does happen. I monitor about 250 threads at once constantly and never really have issues. Did your computer crash? that's the only time i've had my threads go missing.

**Comment by githubisforcingmetodothis** [comment]
The program started working again without any explanation, which makes some network related issue be the most likely explanation, but whatever network issue it might have been, it was only affecting this program as other loaders and programs were detecting all pictures just fine. I am not sure what that means for the program, but it is back to working as it should and I thank you for all the work you are putting into this.

If I'm not mistaken, I have attached the log file anyway, perhaps it will contain some insight into why it was doing what it was doing (or rather, not doing).

**Comment by SuperGouge** [comment]
Thanks for the feedback. However, I don't see any attachment.
