### ISSUE TITLE
Multi-select edit threads

### ISSUE THREAD

**Issue by jwshields** [SuperGouge/ChanThreadWatch#71]
I was digging through the code in frmChanThreadWatch.cs & frmThreadEdit.cs
Specifically the two private voids on line 362 & 574 in frmChanThreadWatch.cs and public class frmThreadEdit starting on line 10 in frmThreadEdit.cs

I'm not versed well enough with C# to know this, but is there any issue in selecting and editing multiple threads at once? (theoretically it would disable changing the description field, and enable editing the category and all the check boxes)
I mainly ask because I just went through about 100 threads and had to check the "Auto-Follow" box on each one by one.

**Comment by SuperGouge** [comment]
Editing multiple threads at the same time is currently not supported.
Some settings cannot be edited while a thread is running, so I'll have to find a way to make the behavior clear to the user in such cases too but I believe this is definitely doable.
