### ISSUE TITLE
putting the subject in folder name

### ISSUE THREAD

**Issue by maskkulin** [SuperGouge/ChanThreadWatch#72]
I'm surprised this isn't implemented yet. When I download threads, folders are only named with board and ID, I would also like to know what the thread is about.

**Comment by SuperGouge** [comment]
This is actually implemented and can be customized in the settings. More info on [the wiki](https://github.com/SuperGouge/ChanThreadWatch/wiki/Features#Thread_Folder_Naming).

**Comment by maskkulin** [comment]
This doesn't work for 8chan, please fix this.
