### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by jdpurcell** [SuperGouge/ChanThreadWatch#74]
I'm the original author of CTW and just wanted to say thanks for maintaining it! I don't really use 4chan anymore, hence the lack of updates.

I linked to your GitHub repo from the official CTW page.

I put the original code on GitHub as well. It's mostly the same as the last official release, but I modernized some of the code to use new language features and fixed the 4chan site helper finally (turned out basically identical to your fix). I also hacked in something kind of unrelated - the ability to download VODs from Twitch (it's actually quite useful for downloading the stream live before Twitch mutes the copyrighted audio segments).

**Comment by hardliner5000** [comment]
Well its me who would like to express my appreciation and always wanted to thank YOU for your great effort. Thank you very much for the great effort and time you spent to share this awesome software with us.

**Comment by SuperGouge** [comment]
Glad to hear from you and indeed thanks for creating this software. Recently I've only been doing small incremental improvements and fixes due to lack of time but I hope to find the time to give CTW a makeover I've been wanting to do for some time, especially concerning the codebase.

If you ever feel like contributing, don't hesitate!

**Comment by jwshields** [comment]
Thank you @jdpurcell and @SuperGouge for both of your work on this. I've been using CTW since around 2009 and it's been a wonderful piece of software and saved me lots of hours (and consumed many many disks)
I greatly appreciate all the work done on it.

**Comment by Sinihopea** [comment]
Thank you very much for your work @jdpurcell and @SuperGouge. And especially for fixing the Linux specific issues that come up every now and then.

**Comment by seagull** [comment]
Holy crap, I thought Jart had vanished off the face of the earth...
I'm the guy who used to host your site.
