### ISSUE TITLE
Image download fails on some chans

### ISSUE THREAD

**Issue by darthfrankfurt** [SuperGouge/ChanThreadWatch#76]
I've found that on 155chan.top, 144chan.ws, and 180chan.info, the downloader fails. It successfully creates a folder and updates it (the downloader doesn't show an error), but it always fails to detect any files to download. Here are three threads (one from each offending site) that have downloadable images that are not detected by the program:

https://155chan.top/sw/res/6320.html
https://144chan.ws/sw/res/8472.html
https://180chan.info/sw/res/9574.html

**Comment by DerSandmann-Badcode** [comment]
I can download files from these URLs, what version of CTW are you running? The latest is 1.15.1.

![image](https://user-images.githubusercontent.com/8218786/37022256-437de620-2187-11e8-9407-dc0d15aa3207.png)

**Comment by darthfrankfurt** [comment]
My sincerest apologies! Upon testing the threads again, they do indeed download correctly. I'm not sure what the problem was earlier, as I was running the latest version at the time. Perhaps it was just my spotty internet connection. In any case, thank you for the response!
