### ISSUE TITLE
Broken after 4channel split

### ISSUE THREAD

**Issue by MaddoScientisto** [SuperGouge/ChanThreadWatch#85]
I don't know if it's still maintained but I'll report it just in case:
4chan got split into 4chan for work unsafe boards and 4channel for work safe boards, the downloader doesn't download images for 4channel, that's all

**Comment by SuperGouge** [comment]
Did you update to 1.17.0?

**Comment by MaddoScientisto** [comment]
woops I didn't haha sorry I went by the dates on the main page and forgot to check the releases, nevermind then
