### ISSUE TITLE
Add multiple threads simultaneously?

### ISSUE THREAD

**Issue by beefykitten** [SuperGouge/ChanThreadWatch#86]
Title is kinda self-explanatory. Say I have several links I wanna add, but I'm too lazy to add them one by one. Any way to make it a simpler, lazy-friendly task?

Thanks.

**Comment by SuperGouge** [comment]
Yes, you can copy a bunch of links to your clipboard (one link per line) and use the button "Add From clipboard". This will add all of the links in the clipboard.
